spring:
  datasource:
    username: root
    password: 201031
    url: jdbc:mysql://localhost:3306/HajiBlog
    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis-plus????????????SQL??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  tomcat:
    max-http-form-post-size: 1GB
